(() => {
  'use strict';
  const W=794,H=1123;
  const groups={
    natureza:{label:'Natureza',icon:'🌿',items:['Sol','Lua e estrelas','Nuvens','Arco-íris','Chuva','Vento','Montanhas','Vulcão','Rio','Cachoeira','Lago','Mar','Praia','Ilha','Floresta','Árvore','Pinheiro','Palmeira','Flor','Jardim','Rosa','Girassol','Tulipa','Margarida','Cacto','Folhas','Sementes','Horta','Cogumelos','Caverna','Campo','Fazenda','Pôr do sol','Nascer do sol','Planeta Terra','Sistema solar','Cometa','Recife de coral','Fundo do mar','Ninho','Colmeia','Teia de aranha','Ciclo da água','Quatro estações','Neve','Tempestade','Frutas na árvore','Pedras e cristais','Estrela cadente','Prado']},
    matematica:{label:'Matemática',icon:'➕',items:Array.from({length:50},(_,i)=>['Soma','Subtração','Multiplicação','Divisão','Formas geométricas','Sequência','Maior e menor','Contagem','Medidas','Problema matemático'][i%10]+' '+(Math.floor(i/10)+1))},
    numeros:{label:'Números',icon:'🔢',items:Array.from({length:50},(_,i)=>'Número '+(i+1))},
    datas:{label:'Datas comemorativas',icon:'🎉',items:['Ano Novo','Carnaval','Dia da Escola','Dia da Mulher','Dia da Água','Páscoa','Dia do Livro Infantil','Povos Indígenas','Tiradentes','Descobrimento do Brasil','Dia do Trabalho','Dia das Mães','Dia da Família','Meio Ambiente','Festa Junina','São João','Dia dos Avós','Dia dos Pais','Dia do Estudante','Folclore','Independência','Dia da Árvore','Primavera','Dia do Trânsito','Dia dos Animais','Dia das Crianças','Dia dos Professores','Halloween','Consciência Negra','Proclamação da República','Dia da Bandeira','Natal','Formatura','Volta às aulas','Aniversário','Amizade','Dia do Abraço','Dia da Paz','Dia do Circo','Dia do Soldado','Dia da Amazônia','Dia da Música','Dia do Livro','Dia da Ciência','Encerramento do ano','Outono','Inverno','Verão','Família na escola','Festa da turma']},
    veiculos:{label:'Veículos',icon:'🚗',items:['Carro','Ônibus','Caminhão','Motocicleta','Bicicleta','Trator','Ambulância','Viatura policial','Caminhão de bombeiros','Táxi','Van escolar','Trem','Metrô','Bonde','Locomotiva','Avião','Helicóptero','Balão','Foguete','Planador','Barco','Navio','Veleiro','Lancha','Submarino','Canoa','Caiaque','Jet ski','Escavadeira','Guindaste','Betoneira','Empilhadeira','Patinete','Skate','Quadriciclo','Kart','Carro de corrida','Fórmula 1','Jipe','Caminhonete','Carro elétrico','Ônibus escolar','Motorhome','Carreta','Triciclo','Dirigível','Balsa','Rebocador','Trator de esteira','Colheitadeira']}
  };
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const slug=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
  function art(key,index,title){
    const n=index+1,mode=index%8;
    const common=`<rect x="28" y="28" width="738" height="1067" rx="24" fill="none" stroke="#111" stroke-width="5"/><path d="M56 126H738" fill="none" stroke="#111" stroke-width="3"/><text x="397" y="88" text-anchor="middle" font-family="Arial" font-size="34" font-weight="700">${esc(title)}</text>`;
    let body='';
    if(key==='numeros') body=`<text x="397" y="670" text-anchor="middle" font-family="Arial" font-size="${n<10?520:360}" font-weight="800" fill="none" stroke="#111" stroke-width="10">${n}</text>`;
    else if(key==='matematica') body=`<g fill="none" stroke="#111" stroke-width="7"><circle cx="260" cy="470" r="95"/><circle cx="535" cy="470" r="95"/><path d="M220 470h80M260 430v80M495 470h80"/><rect x="170" y="680" width="454" height="180" rx="25"/><path d="M230 770h330"/></g>`;
    else if(key==='veiculos') body=`<g fill="none" stroke="#111" stroke-width="7" stroke-linejoin="round"><path d="M150 700h500l-45-190H280l-80 90z"/><circle cx="260" cy="735" r="62"/><circle cx="545" cy="735" r="62"/><path d="M310 510v190M455 510v190"/></g>`;
    else if(key==='natureza') body=mode%2?`<g fill="none" stroke="#111" stroke-width="7"><rect x="360" y="610" width="74" height="250" rx="8"/><circle cx="397" cy="460" r="170"/><circle cx="280" cy="520" r="105"/><circle cx="515" cy="520" r="105"/></g>`:`<g fill="none" stroke="#111" stroke-width="7"><circle cx="397" cy="500" r="110"/>${Array.from({length:12},(_,i)=>{const a=i*Math.PI/6;return `<line x1="${397+Math.cos(a)*150}" y1="${500+Math.sin(a)*150}" x2="${397+Math.cos(a)*220}" y2="${500+Math.sin(a)*220}"/>`}).join('')}<path d="M120 860Q250 790 397 860Q545 790 675 860"/></g>`;
    else body=`<g fill="none" stroke="#111" stroke-width="7"><rect x="235" y="520" width="324" height="280" rx="22"/><path d="M235 610h324M397 520v280M235 520Q315 390 397 520Q480 390 559 520"/><circle cx="397" cy="390" r="55"/></g>`;
    return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="210mm" height="297mm" role="img" aria-label="${esc(title)}"><rect width="794" height="1123" fill="#fff"/>${common}${body}<text x="397" y="1060" text-anchor="middle" font-family="Arial" font-size="22" font-weight="600">Pinte com criatividade!</text></svg>`;
  }
  function download(svg,title){const b=new Blob([svg],{type:'image/svg+xml'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=slug(title)+'-teacheasy.svg';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
  function printOne(svg,title){const w=window.open('','_blank');if(!w)return;w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>@page{size:A4 portrait;margin:10mm}body{margin:0}.sheet{width:190mm;height:277mm}.sheet svg{width:100%;height:100%;display:block}</style></head><body><div class="sheet">${svg}</div><script>onload=()=>setTimeout(()=>print(),200)<\/script></body></html>`);w.document.close()}
  function preview(key,index){const title=groups[key].items[index],svg=art(key,index,title);let d=document.querySelector('#coloring-preview-dialog');if(!d){d=document.createElement('dialog');d.id='coloring-preview-dialog';d.className='coloring-preview-dialog';d.innerHTML='<button class="coloring-preview-close" aria-label="Fechar">×</button><div class="coloring-preview-sheet"></div><div class="coloring-preview-actions"><button class="btn btn-outline print-one">Imprimir A4</button><button class="btn btn-primary download-one">Baixar SVG</button></div>';document.body.appendChild(d);d.querySelector('.coloring-preview-close').onclick=()=>d.close();d.onclick=e=>{if(e.target===d)d.close()}}d.querySelector('.coloring-preview-sheet').innerHTML=svg;d.querySelector('.print-one').onclick=()=>printOne(svg,title);d.querySelector('.download-one').onclick=()=>download(svg,title);d.showModal()}
  function render(container){let active='natureza';container.innerHTML='<div class="coloring-library"><div class="coloring-library-summary"><strong>250 desenhos A4</strong><span>50 desenhos em cada categoria</span></div><div class="coloring-category-tabs"></div><div class="coloring-toolbar"><div><strong class="coloring-current-title"></strong><div class="coloring-current-count"></div></div><div class="coloring-toolbar-actions"><button class="btn btn-primary print-category">Imprimir categoria</button></div></div><div class="coloring-grid"></div></div>';const tabs=container.querySelector('.coloring-category-tabs');Object.entries(groups).forEach(([k,g])=>{const b=document.createElement('button');b.className='coloring-category-tab';b.innerHTML=`${g.icon}<br>${g.label}`;b.onclick=()=>{active=k;draw()};tabs.appendChild(b)});function draw(){const g=groups[active];[...tabs.children].forEach((b,i)=>b.classList.toggle('active',Object.keys(groups)[i]===active));container.querySelector('.coloring-current-title').textContent=g.label;container.querySelector('.coloring-current-count').textContent='50 desenhos prontos para visualizar, baixar e imprimir';const grid=container.querySelector('.coloring-grid');grid.innerHTML='';g.items.forEach((title,i)=>{const svg=art(active,i,title),card=document.createElement('article');card.className='coloring-card';card.innerHTML=`<button class="coloring-thumb" aria-label="Visualizar ${esc(title)}">${svg}</button><div class="coloring-card-copy"><strong>${esc(title)}</strong><span>Folha A4</span></div><div class="coloring-card-actions"><button class="btn btn-outline view">Visualizar</button><button class="btn btn-primary down">Baixar</button></div>`;card.querySelector('.coloring-thumb').onclick=()=>preview(active,i);card.querySelector('.view').onclick=()=>preview(active,i);card.querySelector('.down').onclick=()=>download(svg,title);grid.appendChild(card)})}container.querySelector('.print-category').onclick=()=>window.print();draw()}
  window.ColoringPages={groups,render,total:Object.values(groups).reduce((s,g)=>s+g.items.length,0)};
})();