import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
const root=path.resolve(import.meta.dirname,'..');
const official='https://cdn.mec.gov.br/basenacionalcomum.mec.gov.br/images/BNCC_EI_EF_110518_versaofinal_site.pdf';
function read(y){const s=y<=5?'fundamental-anos-iniciais':'fundamental-anos-finais';return JSON.parse(fs.readFileSync(path.join(root,'data','atividades',s,y+'-ano','4-bimestre','historia.json'),'utf8'));}
test('História do 4º bimestre possui 50 atividades V2 por ano e 450 no total',()=>{const ids=new Set(),titles=new Set(),prompts=new Set();let ac=0,qc=0,rc=0;for(let y=1;y<=9;y++){const c=read(y);assert.equal(c.quantidadeAtividades,50);assert.equal(c.atividades.length,50);assert.equal(c.padraoPedagogico,'teacheasy-v2');assert.equal(c.referenciaBnccUrl,official);assert.equal(c.revisaoPedagogicaHumana,'pendente');assert.deepEqual(c.layout,{formato:'A4',margensCm:1,moldura:'preta',gabarito:'separado'});for(const a of c.atividades){ac++;qc+=a.questoes.length;rc+=a.gabarito.length;assert.equal(a.questoes.length,8);assert.equal(a.gabarito.length,8);assert.ok(a.textoApoio.conteudo.trim().length>80);assert.equal(a.ilustracao.status,'producao-visual-pendente');assert.equal(a.revisao.pedagogicaHumanaConcluida,false);assert.match(a.bncc[0].codigo,new RegExp('^EF0?'+y+'HI\\d{2}$'));assert.ok(!ids.has(a.id));ids.add(a.id);assert.ok(!titles.has(a.titulo));titles.add(a.titulo);for(const q of a.questoes){assert.ok(!/EF\d{2}HI\d{2}/.test(q.enunciado));assert.ok(!prompts.has(q.enunciado));prompts.add(q.enunciado);}}}assert.equal(ac,450);assert.equal(qc,3600);assert.equal(rc,3600);assert.equal(ids.size,450);assert.equal(titles.size,450);assert.equal(prompts.size,3600);});
test('catálogo aponta 50 atividades canônicas de História no 4º bimestre',()=>{const code=fs.readFileSync(path.join(root,'library-catalog.js'),'utf8');const context={};vm.createContext(context);vm.runInContext(code,context);const es=context.TeachEasyLibraryCatalog.entries.filter(e=>e.subject==='História'&&e.term===4);assert.equal(es.length,9);for(const e of es){assert.equal(e.count,50);assert.ok(e.path.endsWith('/4-bimestre/historia.json'));}});
